name: rlabs
channels:
  - conda-forge
  - plotly
dependencies:
  - python==3.9.13
  - pandas==1.4.4
  - scikit-learn==1.1.2
  - requests==2.28.1
  - tqdm==4.64.1
  - hdbscan==0.8.29
  # Interactive
  - jupyter==1.0.0
  - matplotlib==3.5.3
  - plotly==5.10.0
  - seaborn==0.12.0
  # Testing
  - pycodestyle==2.9.1
  - pytest==7.1.3
  - pytest-cov==3.0.0
  - pytest-pycodestyle==2.2.0
  # Pip
  - pip==22.2.2
  - pip:
